### ISSUE TITLE
Atributos privados na classe *User*

### ISSUE THREAD

**Issue by pauloafpjunior** [otaviolemos/thewisedev-mailing#2]
Para manter a padronização com as demais classes (_Name_ e _Email_) e aprimorar o encapsulamento, os atributos da classe _User_ poderiam ser privados (_private_). Fiz um _pull request_ apresentando a maneira como isso poderia ser implementado, mas você pode rejeitá-lo, se quiser. É só uma dica mesmo ;)

**Comment by otaviolemos** [comment]
Oi Paulo, eu tinha pensado nisso mas achei mais simples deixar public
readonly para economizar em código.

O bom do JS/TS é que se eu quiser colocar um get depois, não quebra o
código, porque não precisa trocar todos user.email por user.getEmail() por
exemplo. É só mudar os nomes dos atributos (exemplo _email) e colocar um
get com nome email.

Em sex, 30 de out de 2020 às 08:32, Paulo Júnior <notifications@github.com>
escreveu:

**Comment by pauloafpjunior** [comment]
É isso mesmo!
