### ISSUE TITLE
Checar nome de usuário preenchido apenas com espaços em branco 

### ISSUE THREAD

**Issue by pauloafpjunior** [otaviolemos/thewisedev-mailing#3]
Ao criar o teste abaixo, ele não passa, pois espaços em branco não são removidos do nome do usuário:
```ts
test('should not create user with invalid name (only blank spaces)', async () => {
    const name = '   '
    const user = User.create({ name: name, email: 'otaviolemos@gmail.com' })
    expect(user).toEqual(left(new InvalidNameError(name)))
  })
```
Alterar o método _validate_ da classe _Name_, como segue:
```ts
static validate (name: string): boolean {
    if (!name || name.trim().length < 2 || name.trim().length > 255) {
      return false
    }
    return true
  }
```

**Comment by otaviolemos** [comment]
Boa, essa validação vale a pena mesmo!

(Mesmo que fazemos ela no JS no frontend, é bom que seja feita no domínio
para ficar autocontido)

Em sex, 30 de out de 2020 às 08:50, Paulo Júnior <notifications@github.com>
escreveu:

**Comment by pauloafpjunior** [comment]
Certo!
